// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DockerComposeExample.Repository.Context;

namespace DockerComposeExample.Repository.Migrations
{
    [DbContext(typeof(DockerComposeExampleDbContext))]
    [Migration("20200725113703_Alter_Pagamento")]
    partial class Alter_Pagamento
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DockerComposeExample.Domain.Models.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("ValorPagamento")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorPagoCliente")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Pagamento");
                });

            modelBuilder.Entity("DockerComposeExample.Domain.Models.TrocoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPagamento")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("TipoItemTroco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorItem")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdPagamento");

                    b.ToTable("TrocoItem");
                });

            modelBuilder.Entity("DockerComposeExample.Domain.Models.TrocoItem", b =>
                {
                    b.HasOne("DockerComposeExample.Domain.Models.Pagamento", "Pagamento")
                        .WithMany("TrocoItems")
                        .HasForeignKey("IdPagamento")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
